/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class milkyway_nativePP_Universe */

#ifndef _Included_milkyway_nativePP_Universe
#define _Included_milkyway_nativePP_Universe
#ifdef __cplusplus
extern "C" {
#endif
#undef milkyway_nativePP_Universe_DIM
#define milkyway_nativePP_Universe_DIM 3L
/*
 * Class:     milkyway_nativePP_Universe
 * Method:    getPositions
 * Signature: ()[[D
 */
JNIEXPORT jobjectArray JNICALL Java_milkyway_nativePP_Universe_getPositions
  (JNIEnv *, jobject);

/*
 * Class:     milkyway_nativePP_Universe
 * Method:    run0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_milkyway_nativePP_Universe_run0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
